name: Manual
on:
  workflow_dispatch:    

jobs:
  weekday_job:
    runs-on: ubuntu-latest
    env:
      EMAIL: mgungora@gmail.com
      PASSWORD: invalid
    steps:
      - name: "Hello world when it's Monday"
        run: npm run test
