name: Manual
on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMAIL: mgungora@gmail.com
      PASSWORD: invalid
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: |
        npm ci
        npm test      
